### ISSUE TITLE
小程序 tip

### ISSUE THREAD

**Issue by hdmy** [hdmy/blog#40]

**Comment by hdmy** [comment]
多处获取/复用的数据应放在 App.globalData 中，方法需挂载在App上

**Comment by hdmy** [comment]
**swiper滑动视图使用** 
```html
<swiper current="{{currentIndex}}" circular="true" bindchange="swiperSwitch">
  <swiper-item style="">
  </swiper-item>
</swiper>
```
```javascript
// 手动修改currentIndex 也会触发，故需要判断是否是触摸
swiperSwitch(e) {
  if (e.detail.source === 'touch') {
    this.setData({
       'currentIndex': e.detail.current
    })
  }
}
```

**Comment by hdmy** [comment]
>背景：
上下布局：可下拉刷新的滚动列表 + 底部tag（如底图）
 情况：
ios 滚动时卡顿明显

- 解决方法1：
```css
view{
overflow:auto;
-webkit-overflow-scrolling: touch;
}
```
bug: 下拉刷新刷新的小三点消失，页面不会向下移，列表底部会出现灰色（同背景色）区域，不推荐
- 解决方法2：
使用scroll-view 组件：
```html
 <scroll-view scroll-y enable-back-to-top="true" bindscrolltoupper="pullDownRefresh"></scroll-view>
```
可实现双击回到顶部及滚动到顶部刷新，bug：由于ios滚动有回弹效果，只要页面仍在滚动，点击任何地方无效
![_20180705163834](https://user-images.githubusercontent.com/20206052/42312047-e311a7be-8071-11e8-910a-cd487305e56e.png)

**Comment by hdmy** [comment]
**scroll-view bug**
1. 不支持 box-shadow
2. 在滚动 scroll-view 时会阻止页面回弹，所以在 scroll-view 中滚动，是无法触发 onPullDownRefresh

**map组件 bug**
1. 在可移动的视图中（即 scroll-view、swiper、picker-view、movable-view） map会悬浮、一起移动
2. map 组件是由客户端创建的原生组件，它的层级是最高的，不能通过 z-index 控制层级

**Comment by hdmy** [comment]
情景：ios scroll-view 内容超出容器高度时，会出现可下拉回弹现象
问题：**实现下拉时背景色和导航栏色一致**
```css
scroll-view{
  background: linear-gradient(@nav 50%, @bg 0);   // 1. 利用背景色设置下拉后的底色
  height:100vh;  // 100%   // 2. 指定高度，使内容溢出，此时滚动仅为内容区域
  .content{
    background:@bg;
  }
}
```
