### ISSUE TITLE
css switch开关、自定义radio

### ISSUE THREAD

**Issue by hdmy** [hdmy/blog#6]
```css
CSS: 
  input[type="checkbox"].switch{
    appearance: none;
    width: 3em;
    height: 1.3em;
    background: #777;
    border-radius: 3em;
    position: relative;
    cursor: pointer;
    outline: none;
    transition: all .2s ease-in-out;
    vertical-align: middle;
  }

  input[type="checkbox"].switch:checked{
    background: #f5009d;
  }

  input[type="checkbox"].switch:after{
    position: absolute;
    content: "";
    width: 1.3em;
    height: 1.3em;
    border-radius: 50%;
    background: #fff;
    box-shadow: 0 0 .25em rgba(0,0,0,.3);
    left: 0;
    transition: left .2s ease-in-out;
  }

  input[type="checkbox"].switch:checked:after{
    left: calc(100% - 1.3em);
  }
```

```html
HTML:
<label for="switch-bg">视频背景</label>
<input id="switch-bg" class="switch switch-bg" type="checkbox" name="BG">
```
------
```css
CSS: 
input[type='radio']:before { /*没被选中时候按钮的样式*/
    z-index: 1;
    content: "";
    display: inline-block;
    background-color: #fff;
    padding:0.3em; /*撑开背景，就是中间那块白色的*/
    cursor: pointer;
    text-align: center;
    position: absolute;
    left: 0;
    top:-0.15em;
    height: 0.25em;
    width: 0.25em;
    border-radius: 50%;
    transition: background-color 250ms ease;
  }

input[type=radio]:checked:before {
    background-color: #f5009d;;
    box-shadow: inset 0 0 0 0.15em #f4f4f4;
  }
```

**Comment by hdmy** [comment]
### css 实现展开、折叠小三角
```css
span {
	position: relative;
	padding: 30px;
	font-size: 28px;
	color: rgba(116, 116, 116, 1);
	line-height: 40px;
	&::after {
		content: '';
		position: absolute;
		right: 0px;
		top: 50% + 4.25px;
		transform: translateY(-50%);
		// transition: top,border-color 0.3s ease;
		width: 0;
		height: 0;
		border: 8.5px solid #747474;
		border-color: #747474 transparent transparent;
	}
	&.up::after {
		border-color: transparent transparent #747474;
		top: 50% - 4.25px;
	}
}
```
